namespace: phpipam
replicaCount: 1
nodeSelector: {}
affinity: {}
tolerations: {}

additionalConfigMaps: []
additionalVolumes: []

phpipam:
  name: phpipam-web
  image:
    repository: phpipam/phpipam-www
    tag: v1.7.3
    pullPolicy: IfNotPresent
  ingress:
    enabled: false
    annotations: {}
      # kubernetes.io/ingress.class: nginx
    extraLabels: {}
    hosts:
      - host: phpipam.example.local
        paths:
          - path: /
            pathType: Prefix      
    tls: []
    # - secretName: phpipam-ssl-certificate
    #   hosts:
     #     - phpipam.example.local
  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5
  env:
    - name: TZ
      value: Europe/Warsaw
    - name: IPAM_DISABLE_INSTALLER
      value: "true"
    - name: IPAM_DATABASE_HOST
      value: phpipam-mysql
    - name: IPAM_DATABASE_WEBHOST
      value: "%"
    - name: IPAM_DATABASE_USER
      valueFrom:
        secretKeyRef:
          key: mysql-username
          name: phpipam-mysql-secret
    - name: IPAM_DATABASE_PASS
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: phpipam-mysql-secret
  service:
    port: 80
    type: ClusterIP

phpipamCron:
  name: phpipam-cron
  image:
    repository: phpipam/phpipam-cron
    tag: v1.7.3
    pullPolicy: IfNotPresent
  env:
    - name: IPAM_DATABASE_HOST
      value: phpipam-mysql
    - name: IPAM_DATABASE_PASS
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: phpipam-mysql-secret
    - name: SCAN_INTERVAL
      value: 1h
    - name: TZ
      value: Europe/Warsaw
  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5

phpipamMysql:
  name: phpipam-mysql
  image:
    repository: percona/percona-server
    tag: 8.0.40
    pullPolicy: IfNotPresent
  persistentVolume:
    enabled: true
    # storageClass: ""
    accessModes:
      - ReadWriteOnce
    size: 4Gi
  volumeMounts:
    mountPath: /var/lib/mysql
  env:
    - name: MYSQL_DATABASE
      value: phpipam
    - name: MYSQL_USER
      valueFrom:
        secretKeyRef:
          key: mysql-username
          name: phpipam-mysql-secret
    - name: MYSQL_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql-password
          name: phpipam-mysql-secret
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: phpipam-mysql-secret
  existingSecret: true
  # mysql-root-password: ""
  # mysqlPassword: ""
  # allowEmptyRootPassword: false
  service:
    port: 3306
    type: ClusterIP
  resources: {}
    # requests:
    #   memory: 128Mi
    #   cpu: 0.1
    # limits:
    #   memory: 256Mi
    #   cpu: 0.5