---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{ .Chart.Name }}-mysql-root-pass: {{ randAlphaNum 10 | b64enc | quote }}
  {{ .Chart.Name }}-mysql-pass: {{ randAlphaNum 10 | b64enc | quote }}