---
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Chart.Name }}-web
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    {{ if .Values.ingress.annotations }}
    {{ toYaml .Values.ingress.annotations | nindent 4 }}
    {{ end }}
spec:
  tls:
    - hosts:
        - {{ .Values.global.domain }}
      secretName: "{{ .Release.Name }}-{{ .Chart.Name }}-cert"
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.phpipam.name }}
                port:
                  number: {{ .Values.phpipam.service.port }}
