---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-secrets
  namespace: {{ .Release.Namespace }}
stringData:
  {{ .Chart.Name }}-mysql-pass: "{{ .Values.global.database.password }}"
