
# This is a basic workflow to help you get started with Actions

name: Auto Reindex

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]
concurrency: reindex
jobs:
  reindex:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
    - uses: actions/checkout@v4
    
    - name: Install helm 3
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash

    - name: Package existing charts
      run: |
        ./index-repository.sh
    
    - name: Commit files
      run: |
        git config --local user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add index.yaml packages/
        git commit -m "Reindex new charts" -a

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        force_with_lease: true
