name: Release Charts

on:
  workflow_run:
    workflows: [Lint and Test Charts]
    branches: [master]
    types: [completed]

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: latest

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.GH_TOKEN }}"